### ISSUE TITLE
Question about ion motion simulation of perovskite solar cells

### ISSUE THREAD

**Issue by JackLin112** [PerovskiteSCModelling/IonMonger#1]
Your paper, a fast and robust numerical scheme for solving models of charge carrier transport and ion vacancy motion in perovskite solar cells, which put forward a new method for ion vacancy motion simulation, is very wonderful. I learned it, and have some questions to consult you.
     Because the finite elements method is difficult, I used the finite difference method to calculate.  But we need the Advanpix’s Multiprecision Computing Toolbox if we use the finite difference method . My questions are as follows. 
     1. I don’t know how to use the Advanpix’s Multiprecision Computing Toolbox exactly. I downloaded the Advanpix’s Multiprecision Computing Toolbox and installed it. I added the file of Advanpix’s Multiprecision Computing Toolbox into the first search path of MATLAB, but it make no difference compared with using MATLAB ode15s to calculate without Advanpix toolbox. I have the difficult of Integral tolerance when I use the MATLAB ode15s to calculate directly. 
2. “In order to make use of Advanpix, you need to ensure that all of the input values are multiprecision”, what do you mean “multiprecision”, do you mean that data type should be “double”, but it’s default in MATLAB.
. Thank you very much.

**Comment by NicolaCourtier** [comment]
This question is about how to use a particular toolbox for Matlab that is not used by the code in this repository.

The toolbox in question is Advanpix's Multiprecision Computing Toolbox, see https://www.advanpix.com/. This toolbox overloads Matlab's native functions with new versions that are able to deal with values of arbitrary precision. In order to make use of this toolbox, one should follow both the Installation and Quick Start instructions at https://www.advanpix.com/documentation/users-manual/. In particular, it is important to ensure that all numbers and matrices are initially defined using the function mp(), so that they are created with the desired multiprecision rather than Matlab's standard numeric type ('double'). When such multiprecision numbers and matrices are used as inputs to functions, this is automatically identified by Advanpix's MCT and the multiprecision versions of the functions are used to produce multiprecision outputs.

It is also worth noting that Matlab's ode15s can return the following error for a number of reasons: "Warning: Failure at t=.... Unable to meet integration tolerances without reducing the step size below the smallest value allowed (...) at time t." From experience, such an error can be the result of a small mistake in the code that describes the ODE problem, which means that the solver is effectively being asked to solve an inconsistent set of equations.
