### ISSUE TITLE
Impedance Spectroscopy Simulation: Undefined function 'construct_protocol' for input arguments of type 'struct'.

### ISSUE THREAD

**Issue by NK-ZZhang** [PerovskiteSCModelling/IonMonger#29]
Hello!
I am trying to use IonMonger to simulate the IS spectra of PSCs, and I met some problems.
I followed the Quick Start Guide to set the parameters and got J-V curves successfully. But when I change the applied_voltage in parameters.m from the default one to the Impedance protocol template, I got some errors.

The following error was repeated tens of times in the command window,

```
Warning: frequency 8 encountered an error
> In parallel_function>make_general_channel/channel_general (line 837)
In parallel.internal.parfor.cppRemoteParallelFunction (line 53)
Undefined function 'construct_protocol' for input arguments of type 'struct'.

Error in IS_solver>IS_measurement (line 158)
    construct_protocol(params,params.light_intensity,params.applied_voltage,...

Error in parallel_function>make_general_channel/channel_general (line 837)
                    O = F(C{:});

Error in parallel.internal.parfor.cppRemoteParallelFunction (line 53)
            [out, outSize] = parallel.internal.pool.optionallySerialize(feval(channel, channelArgs{:}));
frequency 8/64 solved in 0.45364s
```

And finally this occured,

```
Unrecognized function or variable 'sols'.

Error in IS_solver (line 91)
for j = 1:length(sols)

Error in master (line 15)
    sol = IS_solver(params);
```

The applied_voltage part in parameters.m, where I have made some changes is showed below,

```
%{
applied_voltage = ...
    {Vbi, ... % steady-state initial value
    'tanh', 5, 1.2, ... % preconditioning
    'linear', 1.2/0.1, 0, ... % reverse scan
    'linear', 1.2/0.1, 1.2 ... % reverse scan
    };
%}

% Impedance protocol template:

applied_voltage = {'impedance', ...
     1e-4, ...     % minimum impedance frequency (Hz)
     1e7, ...      % maximum impedance frequency (Hz)
     0.9, ...      % DC voltage (V)
     10e-3, ...    % AC voltage amplitude (V)
     64, ...       % number of frequencies to sample
     5};           % number of sine waves

reduced_output = true; % set to true to reduce the amount of data retained ...
% in impedance simulations

% Choose whether the time points are spaced linearly or logarithmically
time_spacing = 'lin'; % set equal to either 'lin' (default) or 'log'
```

I am using MATLAB R2023a, academic version. I wonder if I missed something important and how to solve this problem.

**Comment by NicolaCourtier** [comment]
Hello! Sorry for the delay and thanks for the detailed report of the issue.

Unfortunately, I am not able to reproduce this error. When I copy your changes to parameters.m and run master; my instance of the code (also using R2023a) runs the set of impedance simulations with no issue in a couple of minutes.

The first error **_"Undefined function 'construct_protocol' for input arguments of type 'struct'."_** is not clear, because this function is also used when simulating a J-V curve, which you say you were able to do. This error will have been repeated 64 times - once for each frequency.

The second error **_"Unrecognized function or variable 'sols'."_** follows from the first because if the subfunction IS_measurement fails then the variable sols is not created.

It is therefore difficult for me to identify the source of the issue. Can you think of anything else you may have changed? To continue diagnosing the bug, I would need to see the whole parameters file.

**Comment by NK-ZZhang** [comment]
Thanks for your reply.
I made some more attempts and now the problem has been solved.

As you said, when you copy my changes to parameters.m and run master, the code runs the set of impedance simulations with no issue. So I assume that the changes made in parameters.m are not the cause of the errors. Then I ran the impedance simulation on an old computer with Matlab and the code ran successfully.
After comparison, I found that the code runs on 8 workers on my computer, but the parallel computing toolbox is not detected on the old computer. Then I disabled parallel computing on my computer by changing "parfor" with "for" in IS_solver.m and the code ran successfully.
I also try to change the default profile in the Parallel Preferences from "Processes" to "Threads", and the code can also run on 8 workers on my computer.

I don't know why but, fortunately, it works and the problem has been solved. I guess it has something to do with the configuration and some settings of my computer.
